const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const hr_assets = new Schema({
  asset_tag: String,
  asset_type: String,
  asset_description: String,
  asset_serial_number: String,
  asset_manufacturer: String,
  asset_brand: String,
  asset_model: String,
  asset_category_name: String,
  asset_sub_category: String,
  asset_condition: String,
  asset_imagefile: String,
  asset_site: String,
  asset_location: String,
  asset_department_code: String,
  asset_setcheck_defualt: String,
  asset_transaction_status: String,
  asset_purchase_order: String,
  asset_reasons: String,
  asset_note: String,
  asset_assign_to: String,
  vendor_number: String,
  purchase_order: String,
  purchase_date: String,
  purchase_cost: String,
  initial_value: String,
  salvage_value: String,
  depriciable_value: String,
  depreciation_frequency: String,
  useful_life_span: String,
  depreciation_cost: String,
  current_cost: String,
  asset_attachment: String,
  asset_approval: String,
  date_added: String,
  data_entry_by: String,
  maintenance_requestor: String,
  sku_code: String,
  sku_number: String,
  MaintenanceDueDate: String,
  maintenance_ticket_no: String,
  unit_of_measurement: String,
  unit_of_measurement_amount: String,
  unit_of_measurement_amount_remaining: String,
  assigned_to_temp: String,
  asset_storage: String,
  depreciation_date: String,
  invoice_number: String,
  notif_date: Date,
  created_at: Date,
  updated_at: Date
});

module.exports = mongoose.model('hr_assets', hr_assets);
